exception_message: 'Пожалуйста введите данные требуемого формата.\n\nПри возникновении трудностей свяжитесь с @nerby1'
maintenance: "В данный момент ведутся технические работы, бот будет доступен в ближайший час."